/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./test.gltf -T -S 
Files: ./test.gltf [55.49MB] > /Users/denniswegereef/Sites/astro-playground/public/models/test-transformed.glb [417.54KB] (99%)
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export function ModelOne(props) {
  const meshRef = useRef()

  const { nodes, materials } = useGLTF("./models/model-one.glb")

  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh geometry={nodes.shell_48.geometry} material={materials["Mat.8"]} />
      <mesh geometry={nodes.brep_450.geometry} material={materials["Mat.9"]} />
      <mesh
        geometry={nodes.Solid_586.geometry}
        material={materials["Mat.10"]}
      />
      <mesh geometry={nodes.Solid_592.geometry} material={materials.Mat} />
      <mesh
        geometry={nodes.Solid_593.geometry}
        material={materials["Mat.17"]}
      />
      <mesh geometry={nodes.brep_41.geometry} material={materials["Mat.1"]} />
      <mesh geometry={nodes.brep_1.geometry} material={materials["Mat.2"]} />
      <mesh geometry={nodes.brep_44.geometry} material={materials["Mat.3"]} />
      <mesh geometry={nodes.brep_43.geometry} material={materials["Mat.4"]} />
      <mesh geometry={nodes.brep_4392.geometry} material={materials["Mat.5"]} />
      <mesh geometry={nodes.shell_49.geometry} material={materials["Mat.6"]} />
      <mesh geometry={nodes.brep_21.geometry} material={materials["Mat.11"]} />
      <mesh
        geometry={nodes.brep_1231.geometry}
        material={materials["Mat.12"]}
      />
      <mesh
        geometry={nodes.Sheet_5911.geometry}
        material={materials["Mat.14"]}
      />
      <mesh
        geometry={nodes["Sheet_5871-Mat15"].geometry}
        material={materials["Mat.15"]}
      />
    </group>
  )
}

useGLTF.preload("./models/model-one.glb")
