/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./model-two.glb -d -T -S 
Files: ./model-two.glb [10.96MB] > /Users/denniswegereef/Sites/astro-playground/public/models/model-two-transformed.glb [681.35KB] (94%)
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

// Mark

export function ModelTwo(props) {
  const { nodes, materials } = useGLTF("./models/model-two.glb")
  return (
    <group {...props} dispose={null}>
      <group position={[-0.704, 0.451, -0.593]} scale={0.001}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials["Mat.19"]} />
        <mesh geometry={nodes.mesh_0_1.geometry} material={materials.Mat} />
        <mesh
          geometry={nodes.mesh_0_2.geometry}
          material={materials["Mat.1"]}
        />
        <mesh
          geometry={nodes.mesh_0_3.geometry}
          material={materials["Mat.3"]}
        />
        <mesh
          geometry={nodes.mesh_0_4.geometry}
          material={materials["Mat.4"]}
        />
        <mesh
          geometry={nodes.mesh_0_5.geometry}
          material={materials["Mat.5"]}
        />
        <mesh
          geometry={nodes.mesh_0_6.geometry}
          material={materials["Mat.6"]}
        />
        <mesh
          geometry={nodes.mesh_0_7.geometry}
          material={materials["Mat.7"]}
        />
        <mesh
          geometry={nodes.mesh_0_8.geometry}
          material={materials["Mat.18"]}
        />
        <mesh
          geometry={nodes.mesh_0_9.geometry}
          material={materials["Mat.8"]}
        />
        <mesh
          geometry={nodes.mesh_0_10.geometry}
          material={materials["Mat.9"]}
        />
        <mesh
          geometry={nodes.mesh_0_11.geometry}
          material={materials["Mat.10"]}
        />
        <mesh
          geometry={nodes.mesh_0_12.geometry}
          material={materials["Mat.11"]}
        />
        <mesh
          geometry={nodes.mesh_0_13.geometry}
          material={materials["Mat.12"]}
        />
        <mesh
          geometry={nodes.mesh_0_14.geometry}
          material={materials["Mat.13"]}
        />
        <mesh
          geometry={nodes.mesh_0_15.geometry}
          material={materials["Mat.14"]}
        />
        <mesh
          geometry={nodes.mesh_0_16.geometry}
          material={materials["Mat.15"]}
        />
        <mesh
          geometry={nodes.mesh_0_17.geometry}
          material={materials["Mat.16"]}
        />
        <mesh
          geometry={nodes.mesh_0_18.geometry}
          material={materials["Mat.17"]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("./models/model-two.glb")
